### ISSUE TITLE
Yet another Code cleanup

### ISSUE THREAD

**Issue by D-Mantrid** [Discarded-Team/Pyndemic#13]
Tasks to do:
- move Controller `.end_turn` method to the Game class`,
- remove `.standard_move` from `test_player.py` (it's weird how did this thing survive),
- remove unused class attributes and module imports,
- fix typos in function and variable names,
- Rename `Player` class to `Character`.
- Restructure source files (see [Trello task](https://trello.com/c/k4Kwd45H)).

**Comment by elgator** [comment]
* remove 'api.py' and 'test_api.py'

**Comment by D-Mantrid** [comment]
@elgator, actually we just have to clean it, but not remove. This module will now contain functions and constants for creating request/response objects.

**Comment by D-Mantrid** [comment]
Creaated `feature/project-restructuring` for this task/
